name: Alipay Cloud Devops Codescan
on:
  push:
jobs:
  stc:   # 安全扫描
    runs-on: ubuntu-latest
    steps:
      - name: codeScan
        uses: layotto/alipay-cloud-devops-codescan@test2023-10-16
        with:
          parent_uid: ${{ secrets.ALI_PID }}
          private_key: ${{ secrets.ALI_PK }}
          code_type: stc  
  sca:   # 开源合规
    runs-on: ubuntu-latest
    needs: stc
    if: ${{ always() }}   # 添加if条件，使得无论stc任务的结果如何都执行sca任务
    steps:
      - name: codeScan
        uses: layotto/alipay-cloud-devops-codescan@test2023-10-16
        with:
          parent_uid: ${{ secrets.ALI_PID }}
          private_key: ${{ secrets.ALI_PK }}
          code_type: sca


