name: Sync with Yuque
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  sync:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get latest commit ID
        id: get_commit_id
        run: echo "::set-output name=commit_id::$(git rev-parse HEAD)"
      
      - name: Call Sync API
        run: |
          curl --location --request POST 'http://127.0.0.1:8777/v1/rest/sync' \
            --header 'Content-Type: application/json' \
            --data '{
                    "ref":"refs/heads/main",
                    "before":"2db1e4f83dd427d12c19996f431d5d24e1d17db6",
                    "after":"1256abc6900c8ddc24e854ceca648c9df7f6172d",
                    "repository":{
                        "id":706020139,
                        "node_id":"R_kgDOKhUDKw",
                        "name":"alipay-test",
                        "full_name":"Duan-0916/alipay-test",
                        "private":false,
                        "owner":{
                            "name":"Duan-0916",
                            "email":"76544421+Duan-0916@users.noreply.github.com",
                            "login":"Duan-0916",
                            "id":76544421,
                            "node_id":"MDQ6VXNlcjc2NTQ0NDIx",
                            "avatar_url":"https://avatars.githubusercontent.com/u/76544421?v=4",
                            "gravatar_id":"",
                            "url":"https://api.github.com/users/Duan-0916",
                            "html_url":"https://github.com/Duan-0916",
                            "followers_url":"https://api.github.com/users/Duan-0916/followers",
                            "following_url":"https://api.github.com/users/Duan-0916/following{/other_user}",
                            "gists_url":"https://api.github.com/users/Duan-0916/gists{/gist_id}",
                            "starred_url":"https://api.github.com/users/Duan-0916/starred{/owner}{/repo}",
                            "subscriptions_url":"https://api.github.com/users/Duan-0916/subscriptions",
                            "organizations_url":"https://api.github.com/users/Duan-0916/orgs",
                            "repos_url":"https://api.github.com/users/Duan-0916/repos",
                            "events_url":"https://api.github.com/users/Duan-0916/events{/privacy}",
                            "received_events_url":"https://api.github.com/users/Duan-0916/received_events",
                            "type":"User",
                            "site_admin":false
                        },
                        "html_url":"https://github.com/Duan-0916/alipay-test",
                        "description":null,
                        "fork":false,
                        "url":"https://github.com/Duan-0916/alipay-test",
                        "forks_url":"https://api.github.com/repos/Duan-0916/alipay-test/forks",
                        "keys_url":"https://api.github.com/repos/Duan-0916/alipay-test/keys{/key_id}",
                        "collaborators_url":"https://api.github.com/repos/Duan-0916/alipay-test/collaborators{/collaborator}",
                        "teams_url":"https://api.github.com/repos/Duan-0916/alipay-test/teams",
                        "hooks_url":"https://api.github.com/repos/Duan-0916/alipay-test/hooks",
                        "issue_events_url":"https://api.github.com/repos/Duan-0916/alipay-test/issues/events{/number}",
                        "events_url":"https://api.github.com/repos/Duan-0916/alipay-test/events",
                        "assignees_url":"https://api.github.com/repos/Duan-0916/alipay-test/assignees{/user}",
                        "branches_url":"https://api.github.com/repos/Duan-0916/alipay-test/branches{/branch}",
                        "tags_url":"https://api.github.com/repos/Duan-0916/alipay-test/tags",
                        "blobs_url":"https://api.github.com/repos/Duan-0916/alipay-test/git/blobs{/sha}",
                        "git_tags_url":"https://api.github.com/repos/Duan-0916/alipay-test/git/tags{/sha}",
                        "git_refs_url":"https://api.github.com/repos/Duan-0916/alipay-test/git/refs{/sha}",
                        "trees_url":"https://api.github.com/repos/Duan-0916/alipay-test/git/trees{/sha}",
                        "statuses_url":"https://api.github.com/repos/Duan-0916/alipay-test/statuses/{sha}",
                        "languages_url":"https://api.github.com/repos/Duan-0916/alipay-test/languages",
                        "stargazers_url":"https://api.github.com/repos/Duan-0916/alipay-test/stargazers",
                        "contributors_url":"https://api.github.com/repos/Duan-0916/alipay-test/contributors",
                        "subscribers_url":"https://api.github.com/repos/Duan-0916/alipay-test/subscribers",
                        "subscription_url":"https://api.github.com/repos/Duan-0916/alipay-test/subscription",
                        "commits_url":"https://api.github.com/repos/Duan-0916/alipay-test/commits{/sha}",
                        "git_commits_url":"https://api.github.com/repos/Duan-0916/alipay-test/git/commits{/sha}",
                        "comments_url":"https://api.github.com/repos/Duan-0916/alipay-test/comments{/number}",
                        "issue_comment_url":"https://api.github.com/repos/Duan-0916/alipay-test/issues/comments{/number}",
                        "contents_url":"https://api.github.com/repos/Duan-0916/alipay-test/contents/{+path}",
                        "compare_url":"https://api.github.com/repos/Duan-0916/alipay-test/compare/{base}...{head}",
                        "merges_url":"https://api.github.com/repos/Duan-0916/alipay-test/merges",
                        "archive_url":"https://api.github.com/repos/Duan-0916/alipay-test/{archive_format}{/ref}",
                        "downloads_url":"https://api.github.com/repos/Duan-0916/alipay-test/downloads",
                        "issues_url":"https://api.github.com/repos/Duan-0916/alipay-test/issues{/number}",
                        "pulls_url":"https://api.github.com/repos/Duan-0916/alipay-test/pulls{/number}",
                        "milestones_url":"https://api.github.com/repos/Duan-0916/alipay-test/milestones{/number}",
                        "notifications_url":"https://api.github.com/repos/Duan-0916/alipay-test/notifications{?since,all,participating}",
                        "labels_url":"https://api.github.com/repos/Duan-0916/alipay-test/labels{/name}",
                        "releases_url":"https://api.github.com/repos/Duan-0916/alipay-test/releases{/id}",
                        "deployments_url":"https://api.github.com/repos/Duan-0916/alipay-test/deployments",
                        "created_at":1697524835,
                        "updated_at":"2023-10-17T06:47:26Z",
                        "pushed_at":1703128126,
                        "git_url":"git://github.com/Duan-0916/alipay-test.git",
                        "ssh_url":"git@github.com:Duan-0916/alipay-test.git",
                        "clone_url":"https://github.com/Duan-0916/alipay-test.git",
                        "svn_url":"https://github.com/Duan-0916/alipay-test",
                        "homepage":null,
                        "size":155,
                        "stargazers_count":0,
                        "watchers_count":0,
                        "language":"Java",
                        "has_issues":true,
                        "has_projects":true,
                        "has_downloads":true,
                        "has_wiki":true,
                        "has_pages":false,
                        "has_discussions":false,
                        "forks_count":2,
                        "mirror_url":null,
                        "archived":false,
                        "disabled":false,
                        "open_issues_count":3,
                        "license":null,
                        "allow_forking":true,
                        "is_template":false,
                        "web_commit_signoff_required":false,
                        "topics":[
                
                        ],
                        "visibility":"public",
                        "forks":2,
                        "open_issues":3,
                        "watchers":0,
                        "default_branch":"main",
                        "stargazers":0,
                        "master_branch":"main"
                    },
                    "pusher":{
                        "name":"Duan-0916",
                        "email":"76544421+Duan-0916@users.noreply.github.com"
                    },
                    "sender":{
                        "login":"Duan-0916",
                        "id":76544421,
                        "node_id":"MDQ6VXNlcjc2NTQ0NDIx",
                        "avatar_url":"https://avatars.githubusercontent.com/u/76544421?v=4",
                        "gravatar_id":"",
                        "url":"https://api.github.com/users/Duan-0916",
                        "html_url":"https://github.com/Duan-0916",
                        "followers_url":"https://api.github.com/users/Duan-0916/followers",
                        "following_url":"https://api.github.com/users/Duan-0916/following{/other_user}",
                        "gists_url":"https://api.github.com/users/Duan-0916/gists{/gist_id}",
                        "starred_url":"https://api.github.com/users/Duan-0916/starred{/owner}{/repo}",
                        "subscriptions_url":"https://api.github.com/users/Duan-0916/subscriptions",
                        "organizations_url":"https://api.github.com/users/Duan-0916/orgs",
                        "repos_url":"https://api.github.com/users/Duan-0916/repos",
                        "events_url":"https://api.github.com/users/Duan-0916/events{/privacy}",
                        "received_events_url":"https://api.github.com/users/Duan-0916/received_events",
                        "type":"User",
                        "site_admin":false
                    },
                    "created":false,
                    "deleted":false,
                    "forced":false,
                    "base_ref":null,
                    "compare":"https://github.com/Duan-0916/alipay-test/compare/2db1e4f83dd4...1256abc6900c",
                    "commits":[
                        {
                            "id":"1256abc6900c8ddc24e854ceca648c9df7f6172d",
                            "tree_id":"016b2dd7d7358cdf8fc330b670fdb37e270131a8",
                            "distinct":true,
                            "message":"Update yuque.yml",
                            "timestamp":"2023-12-21T11:08:46+08:00",
                            "url":"https://github.com/Duan-0916/alipay-test/commit/1256abc6900c8ddc24e854ceca648c9df7f6172d",
                            "author":{
                                "name":"Duan-0916",
                                "email":"76544421+Duan-0916@users.noreply.github.com",
                                "username":"Duan-0916"
                            },
                            "committer":{
                                "name":"GitHub",
                                "email":"noreply@github.com",
                                "username":"web-flow"
                            },
                            "added":[
                
                            ],
                            "removed":[
                
                            ],
                            "modified":[
                                ".github/workflows/yuque.yml"
                            ]
                        }
                    ],
                    "head_commit":{
                        "id":"1256abc6900c8ddc24e854ceca648c9df7f6172d",
                        "tree_id":"016b2dd7d7358cdf8fc330b670fdb37e270131a8",
                        "distinct":true,
                        "message":"Update yuque.yml",
                        "timestamp":"2023-12-21T11:08:46+08:00",
                        "url":"https://github.com/Duan-0916/alipay-test/commit/1256abc6900c8ddc24e854ceca648c9df7f6172d",
                        "author":{
                            "name":"Duan-0916",
                            "email":"76544421+Duan-0916@users.noreply.github.com",
                            "username":"Duan-0916"
                        },
                        "committer":{
                            "name":"GitHub",
                            "email":"noreply@github.com",
                            "username":"web-flow"
                        },
                        "added":[
                
                        ],
                        "removed":[
                
                        ],
                        "modified":[
                            ".github/workflows/yuque.yml"
                        ]
                    }
              }'
