name: Publish to Preview Knowledge Base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish_to_preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Publish to Preview Knowledge Base
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
              "yuqueNamespace": "eg6z1a/qpbul9",
              "yuqueSite": "https://mosn-layotto.yuque.com/"
          }' http://localhost:8080/sync
