name: Sync with Yuque

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Call Sync API
      run: |
        curl --location 'http://localhost:8888/v1/rest/sync' \
          --header 'Content-Type: application/json' \
          --data '{
            "inputs": {
              "yuqueNamespace": "eg6z1a/qpbul9",
              "yuqueSite": "https://mosn-layotto.yuque.com/"
            }
          }'
