name: Sync with Yuque
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get latest commit ID
        id: get_commit_id
        run: echo "::set-output name=commit_id::$(git rev-parse HEAD)"
      
      - name: Call Sync API
        run: |
          ping 47.243.86.137 -c 3
          curl --location --request POST 'http://47.243.86.137:8777/v1/rest/sync' \
            --header 'Content-Type: application/json' \
            --data '{
              "inputs": {
                "yuqueNamespace": "eg6z1a/qpbul9",
                "yuqueSite": "https://mosn-layotto.yuque.com/",
                "yuqueToken":"TOdAggX2qQA20byXdw1qmfiJ2INwgATyf0uCUUM9",
                "gitRepo": "https://github.com/${{ github.repository }}",
                "gitDocRoot": "/",
                "gitDocToc": "SUMMARY.md",
                "gitCommitId": "${{ steps.get_commit_id.outputs.commit_id }}",
                "gitBranch": "main"
              }
            }'
